In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
diet = pd.read_csv('datasets/diet.csv')
diet

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
0,73557,16888.327864,12930.890649,1,49.0,2.0,2.0,6.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,73558,17932.143865,12684.148869,1,59.0,2.0,2.0,4.0,1.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
2,73559,59641.812930,39394.236709,1,49.0,2.0,2.0,18.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,73560,142203.069917,125966.366442,1,54.0,2.0,2.0,21.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561,59052.357033,39004.892993,1,63.0,2.0,2.0,18.0,1.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9808,83727,14146.781331,10520.302070,1,59.0,2.0,2.0,8.0,7.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
9809,83728,38750.761193,51815.103262,1,25.0,2.0,2.0,9.0,5.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9810,83729,15272.505199,10401.781170,1,59.0,2.0,2.0,1.0,6.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
9811,83730,0.000000,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9812,83731,5805.674812,4339.132077,1,49.0,2.0,2.0,12.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
demographic = pd.read_csv('datasets/demographic.csv')
demographic

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
0,73557,8,2,1,69,NaN,4,4,1.0,NaN,...,3.0,4.0,NaN,13281.237386,13481.042095,1,112,4.0,4.0,0.84
1,73558,8,2,1,54,NaN,3,3,1.0,NaN,...,3.0,1.0,1.0,23682.057386,24471.769625,1,108,7.0,7.0,1.78
2,73559,8,2,1,72,NaN,3,3,2.0,NaN,...,4.0,1.0,3.0,57214.803319,57193.285376,1,109,10.0,10.0,4.51
3,73560,8,2,1,9,NaN,3,3,1.0,119.0,...,3.0,1.0,4.0,55201.178592,55766.512438,2,109,9.0,9.0,2.52
4,73561,8,2,2,73,NaN,3,3,1.0,NaN,...,5.0,1.0,5.0,63709.667069,65541.871229,2,116,15.0,15.0,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10170,83727,8,2,1,26,NaN,2,2,2.0,NaN,...,3.0,NaN,NaN,27141.631824,28115.568221,1,104,77.0,77.0,NaN
10171,83728,8,2,2,2,24.0,1,1,2.0,24.0,...,3.0,1.0,3.0,15274.475360,16512.138781,1,107,8.0,8.0,1.95
10172,83729,8,2,2,42,NaN,4,4,2.0,NaN,...,5.0,3.0,NaN,24122.248900,26902.344381,1,104,7.0,7.0,3.66
10173,83730,8,2,1,7,NaN,2,2,1.0,84.0,...,4.0,1.0,3.0,25521.878546,26686.025573,2,109,6.0,6.0,1.05
10174,83731,8,2,1,11,NaN,5,6,1.0,140.0,...,5.0,1.0,5.0,8930.180154,9700.873491,2,106,15.0,15.0,5.00

In [61]:
examination = pd.read_csv('datasets/examination.csv')
examination

,SEQN,PEASCST1,PEASCTM1,PEASCCT1,BPXCHR,BPAARM,BPACSZ,BPXPLS,BPXPULS,BPXPTY,...,CSXLEAOD,CSXSOAOD,CSXGRAOD,CSXONOD,CSXNGSOD,CSXSLTRT,CSXSLTRG,CSXNART,CSXNARG,CSAEFFRT
0,73557,1,620.0,NaN,NaN,1.0,4.0,86.0,1.0,1.0,...,2.0,1.0,1.0,1.0,4.0,62.0,1.0,NaN,NaN,1.0
1,73558,1,766.0,NaN,NaN,1.0,4.0,74.0,1.0,1.0,...,3.0,1.0,2.0,3.0,4.0,28.0,1.0,NaN,NaN,1.0
2,73559,1,665.0,NaN,NaN,1.0,4.0,68.0,1.0,1.0,...,2.0,1.0,2.0,3.0,4.0,49.0,1.0,NaN,NaN,3.0
3,73560,1,803.0,NaN,NaN,1.0,2.0,64.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561,1,949.0,NaN,NaN,1.0,3.0,92.0,1.0,1.0,...,3.0,1.0,4.0,3.0,4.0,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9808,83727,1,611.0,NaN,NaN,1.0,3.0,60.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9809,83728,1,124.0,NaN,110.0,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9810,83729,1,679.0,NaN,NaN,1.0,4.0,80.0,1.0,1.0,...,1.0,1.0,1.0,3.0,4.0,55.0,1.0,NaN,NaN,3.0
9811,83730,1,381.0,NaN,72.0,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9812,83731,1,498.0,NaN,NaN,1.0,3.0,90.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
labs = pd.read_csv('datasets/labs.csv')
labs

,SEQN,URXUMA,URXUMS,URXUCR.x,URXCRS,URDACT,WTSAF2YR.x,LBXAPB,LBDAPBSI,LBXSAL,...,URXUTL,URDUTLLC,URXUTU,URDUTULC,URXUUR,URDUURLC,URXPREG,URXUAS,LBDB12,LBDB12SI
0,73557,4.3,4.3,39.0,3447.6,11.03,NaN,NaN,NaN,4.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,524.0,386.7
1,73558,153.0,153.0,50.0,4420.0,306.00,NaN,NaN,NaN,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,507.0,374.2
2,73559,11.9,11.9,113.0,9989.2,10.53,142196.890197,57.0,0.57,3.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,732.0,540.2
3,73560,16.0,16.0,76.0,6718.4,21.05,NaN,NaN,NaN,NaN,...,0.062,0.0,0.238,0.0,0.0071,0.0,NaN,3.83,NaN,NaN
4,73561,255.0,255.0,147.0,12994.8,173.47,142266.006548,92.0,0.92,4.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225.0,166.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9808,83727,1.9,1.9,47.0,4154.8,4.04,67775.162806,88.0,0.88,4.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,720.0,531.4
9809,83728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9810,83729,6.0,6.0,117.0,10342.8,5.13,NaN,NaN,NaN,4.1,...,0.135,0.0,0.132,0.0,0.0081,0.0,2.0,9.75,388.0,286.3
9811,83730,4.5,4.5,86.0,7602.4,5.23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9812,83731,5.3,5.3,114.0,10077.6,4.65,NaN,NaN,NaN,NaN,...,0.242,0.0,0.932,0.0,0.0061,0.0,NaN,7.25,NaN,NaN

In [63]:
common_seqn = set(demographic["SEQN"]) & set(diet["SEQN"]) & set(examination["SEQN"])

demographic = demographic[demographic["SEQN"].isin(common_seqn)]
diet = diet[diet["SEQN"].isin(common_seqn)]
examination = examination[examination["SEQN"].isin(common_seqn)]

demographic.to_csv("datasets/filtered_demographic.csv", index=False)
diet.to_csv("datasets/filtered_diet.csv", index=False)
examination.to_csv("datasets/filtered_examination.csv", index=False)

print("Datasets filtered and saved successfully.")

Datasets filtered and saved successfully.

In [64]:
demo = pd.read_csv('datasets/filtered_demographic.csv')
diet = pd.read_csv('datasets/filtered_diet.csv')
exam = pd.read_csv('datasets/filtered_examination.csv')

In [65]:
diet = diet.sort_values('SEQN')
df = diet.merge(demo, on='SEQN').merge(exam, on='SEQN')

In [66]:
df.to_csv('datasets/final_data.csv')

In [67]:
to_encode = [i for i in df.columns if df[i].dtype == 'object']

In [68]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error

# Load datasets
final_data_path = "datasets/final_data.csv"
fitness_data_path = "datasets/fitness_data.csv"
final_df = pd.read_csv(final_data_path)
fitness_df = pd.read_csv(fitness_data_path)

# Drop the first unnamed column if present
final_df = final_df.drop(columns=['Unnamed: 0'], errors='ignore')

# Rename columns in fitness_df for consistency
fitness_df.rename(columns={'Current Weight (kg)': 'Weight (kg)'}, inplace=True)

# Define features and target variable
X = fitness_df[['Body Fat %', 'Weight (kg)', 'Gender']]  # Features
y = fitness_df['Time to Target (wks)']  # Target

# Handle missing values using mean imputation
imputer = SimpleImputer(strategy='mean')
X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# Impute target column (reshape to 2D, then flatten back)
y_imputed = imputer.fit_transform(y.values.reshape(-1, 1)).flatten()

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y_imputed, test_size=0.2, random_state=42)

# Train a Random Forest model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
predictions = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, predictions)
print(f"Mean Absolute Error: {mae}")

Mean Absolute Error: 1.827071428571428

In [69]:
df2_merged = pd.read_csv('datasets/final_data_with_predictions_merged.csv')

In [70]:
column_mapping = {
    "SEQN": "Participant ID",
    "WTDRD1": "Day 1 Weight",
    "WTDR2D": "Two-Day Weight",
    "DR1DRSTZ": "Dietary Status",
    "DR1EXMER": "Examined Respondent",
    "DRABF": "Breastfeeding",
    "DRDINT": "Dietary Interview",
    "DR1DBIH": "Interview Hour",
    "DR1DAY": "Interview Day",
    "DR1LANG": "Interview Language",
    "DR1MNRSP": "Minor Respondent",
    "DR1HELPD": "Dietary Help",
    "DBQ095Z": "Sugar Drinks",
    "DBD100": "Breakfast Consumption",
    "DRQSPREP": "Meal Prep",
    "DR1STY": "Eating Style",
    "DR1SKY": "Skipped Meals",
    "DRQSDIET": "Special Diet",
    "DR1TNUMF": "Food Count",
    "DR1TKCAL": "Total Calories",
    "DR1TPROT": "Protein Intake",
    "DR1TCARB": "Carb Intake",
    "DR1TSUGR": "Sugar Intake",
    "DR1TFIBE": "Fiber Intake",
    "DR1TTFAT": "Total Fat",
    "DR1TSFAT": "Saturated Fat",
    "DR1TMFAT": "Monounsaturated Fat",
    "DR1TPFAT": "Polyunsaturated Fat",
    "DR1TCHOL": "Cholesterol",
    "DR1TATOC": "Alpha Tocopherol",
    "DR1TATOA": "Vitamin A",
    "DR1TRET": "Retinol",
    "DR1TVARA": "Vitamin A (RAE)",
    "DR1TACAR": "Alpha Carotene",
    "DR1TBCAR": "Beta Carotene",
    "DR1TCRYP": "Cryptoxanthin",
    "DR1TLYCO": "Lycopene",
    "DR1TLZ": "Lutein Zeaxanthin",
    "DR1TVB1": "Vitamin B1",
    "DR1TVB2": "Vitamin B2",
    "DR1TNIAC": "Niacin",
    "DR1TVB6": "Vitamin B6",
    "DR1TFOLA": "Folate",
    "DR1TFA": "Folic Acid",
    "DR1TFF": "Food Folate",
    "DR1TFDFE": "Dietary Folate",
    "DR1TCHL": "Choline",
    "DR1TVB12": "Vitamin B12",
    "DR1TB12A": "B12 Added",
    "DR1TVC": "Vitamin C",
    "DR1TVD": "Vitamin D",
    "DR1TVK": "Vitamin K",
    "DR1TCALC": "Calcium",
    "DR1TPHOS": "Phosphorus",
    "DR1TMAGN": "Magnesium",
    "DR1TIRON": "Iron",
    "DR1TZINC": "Zinc",
    "DR1TCOPP": "Copper",
    "DR1TSODI": "Sodium",
    "DR1TPOTA": "Potassium",
    "DR1TSELE": "Selenium",
    "DR1TCAFF": "Caffeine",
    "DR1TTHEO": "Theobromine",
    "DR1TALCO": "Alcohol",
    "DR1TMOIS": "Moisture",
    "SDDSRVYR": "Survey Year",
    "RIDSTATR": "Interview Status",
    "RIAGENDR": "Gender",
    "RIDAGEYR": "Age (Years)",
    "RIDAGEMN": "Age (Months)",
    "RIDRETH1": "Ethnicity",
    "RIDRETH3": "Race/Ethnicity",
    "RIDEXMON": "Exam Month",
    "RIDEXAGM": "Age Group",
    "DMQMILIZ": "Military Status",
    "DMQADFC": "Armed Forces",
    "DMDBORN4": "Birth Country",
    "DMDCITZN": "Citizenship",
    "DMDYRSUS": "Years in US",
    "DMDEDUC3": "Education Level",
    "DMDEDUC2": "Education (Adults)",
    "DMDMARTL": "Marital Status",
    "WTINT2YR": "Interview Weight",
    "WTMEC2YR": "MEC Weight",
    "SDMVPSU": "Pseudo PSU",
    "SDMVSTRA": "Stratum",
    "INDHHIN2": "Household Income",
    "INDFMIN2": "Family Income",
    "INDFMPIR": "Poverty Index",
    "BMXWT": "Body Weight",
    "BMXHT": "Body Height",
    "BMXBMI": "BMI",
    "BMXWAIST": "Waist Size",
    "BMXLEG": "Leg Length",
    "BMXARML": "Arm Length",
    "BMXARMC": "Arm Circumference",
    "BPXSY1": "Systolic BP1",
    "BPXDI1": "Diastolic BP1",
    "BPXSY2": "Systolic BP2",
    "BPXDI2": "Diastolic BP2",
    "BPXSY3": "Systolic BP3",
    "BPXDI3": "Diastolic BP3",
    "BPXSY4": "Systolic BP4",
    "BPXDI4": "Diastolic BP4",
    "BPXPLS": "Pulse Rate",
    "BPXPULS": "Pulse Type",
    "BPXCHR": "Chest Measure",
    "BPXML1": "BP Arm Length",
    "OHXIMP": "Oral Health",
    "OHX01TC": "Tooth Count 1",
    "OHX02TC": "Tooth Count 2",
    "OHX03TC": "Tooth Count 3",
    "OHX04TC": "Tooth Count 4",
    "OHX05TC": "Tooth Count 5",
    "OHX06TC": "Tooth Count 6",
    "OHX07TC": "Tooth Count 7",
    "OHX08TC": "Tooth Count 8",
    "OHX09TC": "Tooth Count 9",
    "OHX10TC": "Tooth Count 10",
    "OHX11TC": "Tooth Count 11",
    "OHX12TC": "Tooth Count 12",
    "OHX13TC": "Tooth Count 13",
    "OHX14TC": "Tooth Count 14",
    "OHX15TC": "Tooth Count 15",
    "OHX16TC": "Tooth Count 16",
    "OHX17TC": "Tooth Count 17",
    "OHX18TC": "Tooth Count 18",
    "OHX19TC": "Tooth Count 19",
    "OHX20TC": "Tooth Count 20",
    "OHX21TC": "Tooth Count 21",
    "OHX22TC": "Tooth Count 22",
    "OHX23TC": "Tooth Count 23",
    "OHX24TC": "Tooth Count 24",
    "OHX25TC": "Tooth Count 25",
    "OHX26TC": "Tooth Count 26",
    "OHX27TC": "Tooth Count 27",
    "OHX28TC": "Tooth Count 28",
    "OHX29TC": "Tooth Count 29",
    "OHX30TC": "Tooth Count 30",
    "OHX31TC": "Tooth Count 31",
    "OHX32TC": "Tooth Count 32"
}

df2_merged.rename(columns=column_mapping, inplace=True)

In [71]:
df2_merged

,Unnamed: 0,Participant ID,Day 1 Weight,Two-Day Weight,Dietary Status,Examined Respondent,Breastfeeding,Dietary Interview,Interview Hour,Interview Day,...,CSXNGSOD,CSXSLTRT,CSXSLTRG,CSXNART,CSXNARG,CSAEFFRT,Height (cm),Current Weight (kg),Predicted Time to Target (wks),Predicted Target Weight (kg)
0,0,73557,16888.327864,12930.890649,1,49.0,2.0,2.0,6.0,2.0,...,4.0,62.0,1.0,NaN,NaN,1.0,171.3,78.3,26.642,64.580
1,1,73558,17932.143865,12684.148869,1,59.0,2.0,2.0,4.0,1.0,...,4.0,28.0,1.0,NaN,NaN,1.0,176.8,89.5,41.934,68.726
2,2,73559,59641.812930,39394.236709,1,49.0,2.0,2.0,18.0,6.0,...,4.0,49.0,1.0,NaN,NaN,3.0,175.3,88.9,42.744,67.593
3,3,73560,142203.069917,125966.366442,1,54.0,2.0,2.0,21.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,137.3,32.2,10.540,49.592
4,4,73561,59052.357033,39004.892993,1,63.0,2.0,2.0,18.0,1.0,...,4.0,NaN,NaN,NaN,NaN,1.0,162.4,52.0,8.784,58.685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10114,9808,83727,14146.781331,10520.302070,1,59.0,2.0,2.0,8.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,171.3,71.8,15.808,64.339
10115,9809,83728,38750.761193,51815.103262,1,25.0,2.0,2.0,9.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,84.4,11.3,10.540,49.592
10116,9810,83729,15272.505199,10401.781170,1,59.0,2.0,2.0,1.0,6.0,...,4.0,55.0,1.0,NaN,NaN,3.0,162.3,89.6,53.776,57.449
10117,9811,83730,0.000000,NaN,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,119.1,22.8,10.540,49.592
10118,9812,83731,5805.674812,4339.132077,1,49.0,2.0,2.0,12.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,148.1,42.3,10.540,49.592

In [72]:
column_mapping_rem = {
    "OHX02CTC": "Tooth Count - Upper Right 2nd Molar",
    "OHX03CTC": "Tooth Count - Upper Right 1st Molar",
    "OHX04CTC": "Tooth Count - Upper Right 2nd Premolar",
    "OHX05CTC": "Tooth Count - Upper Right 1st Premolar",
    "OHX06CTC": "Tooth Count - Upper Right Canine",
    "OHX07CTC": "Tooth Count - Upper Right Lateral Incisor",
    "OHX08CTC": "Tooth Count - Upper Right Central Incisor",
    "OHX09CTC": "Tooth Count - Upper Left Central Incisor",
    "OHX10CTC": "Tooth Count - Upper Left Lateral Incisor",
    "OHX11CTC": "Tooth Count - Upper Left Canine",
    "OHX12CTC": "Tooth Count - Upper Left 1st Premolar",
    "OHX13CTC": "Tooth Count - Upper Left 2nd Premolar",
    "OHX14CTC": "Tooth Count - Upper Left 1st Molar",
    "OHX15CTC": "Tooth Count - Upper Left 2nd Molar",
    "OHX16CTC": "Tooth Count - Upper Left 3rd Molar",
    "OHX17CTC": "Tooth Count - Lower Left 3rd Molar",
    "OHX18CTC": "Tooth Count - Lower Left 2nd Molar",
    "OHX19CTC": "Tooth Count - Lower Left 1st Molar",
    "OHX20CTC": "Tooth Count - Lower Left 2nd Premolar",
    "OHX21CTC": "Tooth Count - Lower Left 1st Premolar",
    "OHX22CTC": "Tooth Count - Lower Left Canine",
    "OHX23CTC": "Tooth Count - Lower Left Lateral Incisor",
    "OHX24CTC": "Tooth Count - Lower Left Central Incisor",
    "OHX25CTC": "Tooth Count - Lower Right Central Incisor",
    "OHX26CTC": "Tooth Count - Lower Right Lateral Incisor",
    "OHX27CTC": "Tooth Count - Lower Right Canine",
    "OHX28CTC": "Tooth Count - Lower Right 1st Premolar",
    "OHX29CTC": "Tooth Count - Lower Right 2nd Premolar",
    "OHX30CTC": "Tooth Count - Lower Right 1st Molar",
    "OHX31CTC": "Tooth Count - Lower Right 2nd Molar",
    "OHX32CTC": "Tooth Count - Lower Right 3rd Molar",
    "OHXIMP": "Oral Health Exam Impression",
    "OHXREST": "Oral Health Restorations",
    "OHXEXM": "Oral Health Exam Status",
    "OHXFLOR": "Fluoride Treatment Status",
    "OHXPER": "Periodontal Health Status",
    "OHXGING": "Gingivitis Status",
    "OHXPLAQ": "Plaque Accumulation Level",
    "OHXTART": "Tartar Accumulation Level",
    "OHXSTAIN": "Tooth Staining Level",
    "OHXDRY": "Oral Dryness Condition",
    "OHXSAL": "Saliva Production Level",
    "OHXBITE": "Bite Alignment Status",
    "OHXBRUX": "Bruxism (Teeth Grinding) Condition",
    "OHXTMJ": "Temporomandibular Joint (TMJ) Disorder",
    "OHXORT": "Orthodontic Treatment Status",
    "OHXEXTR": "Tooth Extraction History",
    "OHXIMPL": "Dental Implant Presence",
    "OHXDENT": "Dentures Presence",
    "OHXBRIDG": "Dental Bridge Presence",
    "OHXSEAL": "Dental Sealants Presence",
    "OHXCAV": "Cavities Presence",
    "OHXFILL": "Dental Fillings Presence",
    "OHXROOT": "Root Canal Treatment Status",
    "OHXPERIO": "Periodontal Disease Diagnosis",
    "OHXGUM": "Gum Disease Status",
    "OHXLOOSE": "Loose Teeth Status",
    "OHXPREG": "Pregnancy-Related Oral Health Issues",
    "OHXSMOKE": "Smoking Effects on Oral Health",
    "OHXDIAB": "Diabetes-Related Oral Health Issues",
    "OHXHEART": "Heart Disease-Related Oral Health Issues",
    "OHXOSTEO": "Osteoporosis-Related Oral Health Issues",
    "OHXMEDS": "Medications Affecting Oral Health",
    "OHXDENTC": "Dental Care Frequency",
    "OHXVISIT": "Dental Visit Frequency",
    "OHXPAIN": "Oral Pain Frequency",
    "OHXBRUSH": "Brushing Frequency",
    "OHXFLOSS": "Flossing Frequency",
    "OHXRINSE": "Mouth Rinse Use Frequency",
    "OHXDIET": "Dietary Impact on Oral Health",
    "OHXSUGR": "Sugar Consumption Level",
    "OHXALC": "Alcohol Consumption Impact on Oral Health",
    "OHXCAFFE": "Caffeine Impact on Oral Health",
    "OHXSNACK": "Snacking Frequency Impact on Oral Health",
    "OHXMEAL": "Meal Frequency Impact on Oral Health",
    "OHXHYGIENE": "Oral Hygiene Routine",
    "OHXEDU": "Oral Health Education Level",
    "OHXINCOME": "Income Level Impact on Oral Health",
    "OHXINSUR": "Dental Insurance Coverage",
    "OHXTRTMT": "Dental Treatment Access",
    "OHXEMERG": "Emergency Dental Care Access",
    "OHXPRV": "Preventive Dental Care Access",
    "OHXCHECK": "Routine Dental Checkups",
    "OHXSATIS": "Satisfaction with Dental Care",
    "OHXANXIETY": "Dental Anxiety Level",
    "OHXSTRESS": "Stress Impact on Oral Health",
    "OHXHABIT": "Oral Habits Impact",
    "CSAEXAM": "Clinical Examination Status",
    "CSAHEALTH": "General Health Condition",
    "CSADIET": "Dietary Habits Impact",
    "CSAPHYS": "Physical Activity Impact",
    "CSAWEIGHT": "Weight Impact on Oral Health",
    "CSABMI": "BMI Impact on Oral Health",
    "CSASMOKE": "Smoking Impact on General Health",
    "CSAALC": "Alcohol Consumption Impact on General Health",
    "CSADISEASE": "Chronic Disease Presence",
    "CSAIMMUNE": "Immune System Condition",
    "CSAAGE": "Age Impact on Health",
    "CSAGENDER": "Gender Differences in Health",
    "CSARACE": "Racial/Ethnic Health Differences",
    "CSAEDU": "Education Level Impact on Health",
    "CSAINCOME": "Income Level Impact on Health",
    "CSAINFRA": "Healthcare Infrastructure Access",
    "CSAINSUR": "Health Insurance Coverage",
    "CSAHEALTHCARE": "Healthcare Access",
    "CSAEFFRT": "Effort in Maintaining Health",
    "OHX02CSC": "Oral Health Exam - Tooth 2 Status",
    "OHX03CSC": "Oral Health Exam - Tooth 3 Status",
    "OHX04CSC": "Oral Health Exam - Tooth 4 Status",
    "OHX05CSC": "Oral Health Exam - Tooth 5 Status",
    "OHX06CSC": "Oral Health Exam - Tooth 6 Status",
    "OHX07CSC": "Oral Health Exam - Tooth 7 Status",
    "OHX08CSC": "Oral Health Exam - Tooth 8 Status",
    "OHX09CSC": "Oral Health Exam - Tooth 9 Status",
    "OHX10CSC": "Oral Health Exam - Tooth 10 Status",
    "OHX11CSC": "Oral Health Exam - Tooth 11 Status",
    "OHX12CSC": "Oral Health Exam - Tooth 12 Status",
    "OHX13CSC": "Oral Health Exam - Tooth 13 Status",
    "OHX14CSC": "Oral Health Exam - Tooth 14 Status",
    "OHX15CSC": "Oral Health Exam - Tooth 15 Status",
    "OHX18CSC": "Oral Health Exam - Tooth 18 Status",
    "OHX19CSC": "Oral Health Exam - Tooth 19 Status",
    "OHX20CSC": "Oral Health Exam - Tooth 20 Status",
    "OHX21CSC": "Oral Health Exam - Tooth 21 Status",
    "OHX22CSC": "Oral Health Exam - Tooth 22 Status",
    "OHX23CSC": "Oral Health Exam - Tooth 23 Status",
    "OHX24CSC": "Oral Health Exam - Tooth 24 Status",
    "OHX25CSC": "Oral Health Exam - Tooth 25 Status",
    "OHX26CSC": "Oral Health Exam - Tooth 26 Status",
    "OHX27CSC": "Oral Health Exam - Tooth 27 Status",
    "OHX28CSC": "Oral Health Exam - Tooth 28 Status",
    "OHX29CSC": "Oral Health Exam - Tooth 29 Status",
    "OHX30CSC": "Oral Health Exam - Tooth 30 Status",
    "OHX31CSC": "Oral Health Exam - Tooth 31 Status",

    # Oral Health Exam - Surface Condition
    "OHX02SE": "Oral Health Exam - Tooth 2 Surface Condition",
    "OHX03SE": "Oral Health Exam - Tooth 3 Surface Condition",
    "OHX04SE": "Oral Health Exam - Tooth 4 Surface Condition",
    "OHX05SE": "Oral Health Exam - Tooth 5 Surface Condition",
    "OHX06SE": "Oral Health Exam - Tooth 6 Surface Condition",
    "OHX07SE": "Oral Health Exam - Tooth 7 Surface Condition",
    "OHX08SE": "Oral Health Exam - Tooth 8 Surface Condition",
    "OHX09SE": "Oral Health Exam - Tooth 9 Surface Condition",
    "OHX10SE": "Oral Health Exam - Tooth 10 Surface Condition",
    "OHX11SE": "Oral Health Exam - Tooth 11 Surface Condition",
    "OHX12SE": "Oral Health Exam - Tooth 12 Surface Condition",
    "OHX13SE": "Oral Health Exam - Tooth 13 Surface Condition",
    "OHX14SE": "Oral Health Exam - Tooth 14 Surface Condition",
    "OHX15SE": "Oral Health Exam - Tooth 15 Surface Condition",
    "OHX18SE": "Oral Health Exam - Tooth 18 Surface Condition",
    "OHX19SE": "Oral Health Exam - Tooth 19 Surface Condition",
    "OHX20SE": "Oral Health Exam - Tooth 20 Surface Condition",
    "OHX21SE": "Oral Health Exam - Tooth 21 Surface Condition",
    "OHX28SE": "Oral Health Exam - Tooth 28 Surface Condition",
    "OHX29SE": "Oral Health Exam - Tooth 29 Surface Condition",
    "OHX30SE": "Oral Health Exam - Tooth 30 Surface Condition",
    "OHX31SE": "Oral Health Exam - Tooth 31 Surface Condition",

    # Examination Status & Comments
    "CSXEXSTS": "Examination Status",
    "CSXEXCMT": "Examination Comment",
    "OHDEXSTS": "Oral Health Exam - Exam Status",
    "OHDDESTS": "Oral Health Exam - Detailed Exam Status",

    # Survey Equipment & Non-Applicable Data
    "CSXQUIPG": "Survey Equipment - Primary Group",
    "CSXQUIPT": "Survey Equipment - Type",
    "CSXNAPG": "Survey Non-Applicable Primary Group",
    "CSXNAPT": "Survey Non-Applicable Type",
    "CSXQUISG": "Survey Questionnaire Subject Group",
    "CSXQUIST": "Survey Questionnaire Subject Type",
    "CSXSLTSG": "Survey Salt Subject Group",
    "CSXSLTST": "Survey Salt Subject Type",
    "CSXNASG": "Survey Non-Applicable Subject Group",
    "CSXNAST": "Survey Non-Applicable Subject Type",

    # Dietary Recall Data
    "DRQSDT1": "Dietary Recall - Day 1 Start Time",
    "DRQSDT2": "Dietary Recall - Day 2 Start Time",
    "DRQSDT91": "Dietary Recall - Total Intake Time",
    "DR1TS040": "Dietary Recall - Meal 1 Time",
    "DR1TS060": "Dietary Recall - Meal 2 Time",
    "DR1TS080": "Dietary Recall - Meal 3 Time",
    "DR1TS100": "Dietary Recall - Meal 4 Time",
    "DR1TS120": "Dietary Recall - Meal 5 Time",
    "DR1TS140": "Dietary Recall - Meal 6 Time",
    "DR1TM161": "Dietary Recall - Total Meal 1 Time",
    "DR1TM181": "Dietary Recall - Total Meal 2 Time",
    "DR1TP182": "Dietary Recall - Total Protein Meal 1",
    "DR1TP183": "Dietary Recall - Total Protein Meal 2",
    "DR1.300": "Dietary Recall - Food Count",
    "DR1.320Z": "Dietary Recall - Total Calories",
    "DR1.330Z": "Dietary Recall - Total Macronutrient Intake",
    "DR1BWATZ": "Dietary Recall - Water Intake",

    # Body Measurements
    "BMDSTATS": "Body Measurement Status",
    "Body Weight": "Body Weight (kg)",
    "BMIWT": "BMI Weight",
    "BMXRECUM": "Recumbent Length",
    "BMIRECUM": "Recumbent BMI",
    "BMXHEAD": "Head Circumference",
    "BMIHEAD": "Head BMI",
    "Body Height": "Body Height (cm)",
    "BMIHT": "BMI Height",
    "BMI": "Body Mass Index (BMI)",
    "BMDBMIC": "BMI Classification",
    "Leg Length": "Leg Length",
    "BMILEG": "BMI Leg Length",
    "Arm Length": "Arm Length",
    "BMIARML": "BMI Arm Length",
    "Waist Size": "Waist Circumference",
    "BMIWAIST": "BMI Waist Circumference",
}


df2_merged.rename(columns=column_mapping_rem, inplace=True)

In [73]:
with open('columns.txt', 'w') as file:
    for i in df2_merged.columns[:-4]:
        file.write(f"{i}\n")

In [74]:
column_mapping_rem2 = {
    "DRQSDT3": "Time of First Dietary Recall Interview",
    "DRQSDT4": "Time of Second Dietary Recall Interview",
    "DRQSDT5": "Duration Between Dietary Recall Interviews",
    "DRQSDT6": "Total Number of Dietary Recall Interviews Completed",
    "DRQSDT7": "Dietary Recall Interview Completion Status",
    "DRQSDT8": "Method of Dietary Recall Data Collection",
    "DRQSDT9": "Use of Dietary Supplements Reported",
    "DRQSDT10": "Frequency of Dietary Supplement Use",
    "DRQSDT11": "Dietary Supplement Use on Interview Day",
    "DRQSDT12": "Type of Dietary Supplement Used",

    "DR1TS160": "Total Sugar Intake (grams)",
    "DR1TS180": "Total Carbohydrate Intake (grams)",
    "DR1TM201": "Total Fat Intake (grams)",
    "DR1TM221": "Total Protein Intake (grams)",
    "DR1TP184": "Total Sodium Intake (milligrams)",
    "DR1TP204": "Total Potassium Intake (milligrams)",
    "DR1TP205": "Total Fiber Intake (grams)",
    "DR1TP225": "Total Calcium Intake (milligrams)",
    "DR1TP226": "Total Iron Intake (milligrams)",
    "DR1TWS": "Total Water Intake (grams)",

    "DRD340": "Dietary Recall Day of the Week",
    "DRD350A": "Breakfast Consumption Status",
    "DRD350AQ": "Breakfast Nutrient Contribution (%)",
    "DRD350B": "Lunch Consumption Status",
    "DRD350BQ": "Lunch Nutrient Contribution (%)",
    "DRD350C": "Dinner Consumption Status",
    "DRD350CQ": "Dinner Nutrient Contribution (%)",
    "DRD350D": "Snack 1 Consumption Status",
    "DRD350DQ": "Snack 1 Nutrient Contribution (%)",
    "DRD350E": "Snack 2 Consumption Status",
    "DRD350EQ": "Snack 2 Nutrient Contribution (%)",
    "DRD350F": "Snack 3 Consumption Status",
    "DRD350FQ": "Snack 3 Nutrient Contribution (%)",
    "DRD350G": "Snack 4 Consumption Status",
    "DRD350GQ": "Snack 4 Nutrient Contribution (%)",
    "DRD350H": "Snack 5 Consumption Status",
    "DRD350HQ": "Snack 5 Nutrient Contribution (%)",
    "DRD350I": "Snack 6 Consumption Status",
    "DRD350IQ": "Snack 6 Nutrient Contribution (%)",
    "DRD350J": "Snack 7 Consumption Status",
    "DRD350JQ": "Snack 7 Nutrient Contribution (%)",
    "DRD350K": "Snack 8 Consumption Status",

    "DRD360": "Total Daily Energy Intake (kcal)",

    "DRD370A": "Protein Contribution to Energy Intake (%)",
    "DRD370AQ": "Carbohydrate Contribution to Energy Intake (%)",
    "DRD370B": "Fat Contribution to Energy Intake (%)",
    "DRD370BQ": "Saturated Fat Contribution to Energy Intake (%)",
    "DRD370C": "Monounsaturated Fat Contribution to Energy Intake (%)",
    "DRD370CQ": "Polyunsaturated Fat Contribution to Energy Intake (%)",
    "DRD370D": "Alcohol Contribution to Energy Intake (%)",
    "DRD370DQ": "Cholesterol Intake (mg)",
    "DRD370E": "Dietary Fiber Intake Contribution (%)",
    "DRD370EQ": "Total Sugar Contribution (%)",
    "DRD370F": "Calcium Contribution to Energy Intake (%)",
    "DRD370FQ": "Iron Contribution to Energy Intake (%)",
    "DRD370G": "Magnesium Contribution to Energy Intake (%)",
    "DRD370GQ": "Phosphorus Contribution to Energy Intake (%)",
    "DRD370H": "Potassium Contribution to Energy Intake (%)",
    "DRD370HQ": "Sodium Contribution to Energy Intake (%)",
    "DRD370I": "Zinc Contribution to Energy Intake (%)",
    "DRD370IQ": "Copper Contribution to Energy Intake (%)",
    "DRD370J": "Selenium Contribution to Energy Intake (%)",
    "DRD370JQ": "Vitamin A Contribution to Energy Intake (%)",
    "DRD370K": "Vitamin C Contribution to Energy Intake (%)",
    "DRD370KQ": "Vitamin D Contribution to Energy Intake (%)",
    "DRD370L": "Vitamin E Contribution to Energy Intake (%)",
    "DRD370LQ": "Vitamin K Contribution to Energy Intake (%)",
    "DRD370M": "Thiamin Contribution to Energy Intake (%)",
    "DRD370MQ": "Riboflavin Contribution to Energy Intake (%)",
    "DRD370N": "Niacin Contribution to Energy Intake (%)",
    "DRD370NQ": "Vitamin B6 Contribution to Energy Intake (%)",
    "DRD370O": "Folate Contribution to Energy Intake (%)",
    "DRD370OQ": "Vitamin B12 Contribution to Energy Intake (%)",
    "DRD370P": "Choline Contribution to Energy Intake (%)",
    "DRD370PQ": "Retinol Contribution to Energy Intake (%)",
    "DRD370Q": "Beta Carotene Contribution to Energy Intake (%)",
    "DRD370QQ": "Alpha Carotene Contribution to Energy Intake (%)",
    "DRD370R": "Lycopene Contribution to Energy Intake (%)",
    "DRD370RQ": "Lutein and Zeaxanthin Contribution to Energy Intake (%)",
    "DRD370S": "Tocopherol Contribution to Energy Intake (%)",
    "DRD370SQ": "Added Sugars Contribution to Energy Intake (%)",
    "DRD370T": "Caffeine Contribution to Energy Intake (%)",
    "DRD370TQ": "Theobromine Contribution to Energy Intake (%)",
    "DRD370U": "Total Fatty Acids Contribution to Energy Intake (%)",
    "DRD370UQ": "Trans Fatty Acids Contribution to Energy Intake (%)",
    "DRD370V": "Total Saturated Fatty Acids Contribution to Energy Intake (%)",

    "RIDEXPRG": "Pregnancy Status",
    "SIALANG": "Primary Language of Household Interview",
    "SIAPROXY": "Proxy Used for Interview",
    "SIAINTRP": "Interpreter Used for Interview",
    "FIALANG": "Primary Language of Family Interview",
    "FIAPROXY": "Proxy Used for Family Interview",
    "FIAINTRP": "Interpreter Used for Family Interview",
    "MIALANG": "Primary Language of Medical Interview",
    "MIAPROXY": "Proxy Used for Medical Interview",
    "MIAINTRP": "Interpreter Used for Medical Interview",
    "AIALANGA": "Primary Language of Audiometry Interview",

    "DMDHHSIZ": "Household Size",
    "DMDFMSIZ": "Family Size",
    "DMDHHSZA": "Number of Children Under 6 Years",
    "DMDHHSZB": "Number of Children 6-17 Years",
    "DMDHHSZE": "Number of Adults 60+ Years",
    "DMDHRGND": "Gender",
    "DMDHRAGE": "Age in Years",
    "DMDHRBR4": "Race/Ethnicity",
    "DMDHREDU": "Education Level",
    "DMDHRMAR": "Marital Status",
    "DMDHSEDU": "Highest Education Level in Household",

    "BMXSAD1": "Upper Arm Skinfold Thickness (mm)",
    "BMXSAD2": "Subscapular Skinfold Thickness (mm)",
    "BMXSAD3": "Triceps Skinfold Thickness (mm)",
    "BMXSAD4": "Sum of Skinfold Thickness (mm)",
    
    "BMDAVSAD": "Average Skinfold Thickness (mm)",
    "BMDSADCM": "Skinfold Measurement Comment Code",
    
    "MGDEXSTS": "Muscle Strength Test Eligibility",
    "MGD050": "Grip Strength Test Performed",
    "MGD060": "Hand Grip Strength (kg)",
    "MGQ070": "Dominant Hand Used for Grip Test",
    "MGQ080": "Average Grip Strength (kg)",
    "MGQ090": "Max Grip Strength (kg)",
    "MGQ100": "Grip Strength - Right Hand (kg)",
    "MGQ110": "Grip Strength - Left Hand (kg)",
    "MGQ120": "Grip Strength Measurement Comment Code",
    "MGD130": "Test Completion Status",
    "MGQ90DG": "Grip Strength Measurement Device Type",
    "MGDSEAT": "Seated Position During Grip Strength Test",
    "MGAPHAND": "Grip Strength - Average of Both Hands (kg)",
    "MGATHAND": "Grip Strength - Average of Dominant Hand (kg)",

    "MGXH1T1": "Standing Height Trial 1 (cm)",
    "MGXH1T1E": "Standing Height Trial 1 Measurement Error",
    "MGXH2T1": "Standing Height Trial 2 (cm)",
    "MGXH2T1E": "Standing Height Trial 2 Measurement Error",
    "MGXH1T2": "Recumbent Length Trial 1 (cm)",
    "MGXH1T2E": "Recumbent Length Trial 1 Measurement Error",
    "MGXH2T2": "Recumbent Length Trial 2 (cm)",
    "MGXH2T2E": "Recumbent Length Trial 2 Measurement Error",
    "MGXH1T3": "Knee Height Trial 1 (cm)",
    "MGXH1T3E": "Knee Height Trial 1 Measurement Error",
    "MGXH2T3": "Knee Height Trial 2 (cm)",
    "MGXH2T3E": "Knee Height Trial 2 Measurement Error",
    
    "MGDCGSZ": "Calibrated Grip Strength Size",
    
    "CSQ245": "Frequency of Socializing with Friends/Family",
    "CSQ241": "Perceived Social Support Level",
    "CSQ260A": "Participation in Social Activities (Last Month)",
    "CSQ260D": "Volunteering Participation",
    "CSQ260G": "Religious or Spiritual Activity Participation",
    "CSQ260I": "Recreational Activity Participation",
    "CSQ260N": "Participation in Support Groups",
    "CSQ260M": "Physical Activity Participation in Groups",
    "CSQ270": "Frequency of Social Media Use",
    "CSQ450": "Loneliness Score",
    "CSQ460": "Stress Level Rating",
    "CSQ470": "Depression Scale Score",
    "CSQ480": "Anxiety Scale Score",
    "CSQ490": "Overall Life Satisfaction Score",
    
    "CSXTSEQ": "Household Smoking Status",
    "CSXCHOOD": "Exposure to Secondhand Smoke - Home",
    "CSXSBOD": "Exposure to Secondhand Smoke - School/Work",
    "CSXSMKOD": "Exposure to Secondhand Smoke - Other Locations",
    "CSXLEAOD": "Lead Exposure Source",
    "CSXSOAOD": "Source of Air Pollution Exposure",
    "CSXGRAOD": "Green Space Availability Around Residence",
    "CSXONOD": "Occupational Noise Exposure",
    "CSXNGSOD": "Gas Stove Usage in Household",
    "CSXSLTRT": "Sleep Quality Rating",
    "CSXSLTRG": "Sleep Duration Per Night (Hours)",
    "CSXNART": "Nap Frequency Per Week",
    "CSXNARG": "Nap Duration (Minutes)"
}

df2_merged.rename(columns=column_mapping_rem2, inplace=True)

with open('columns.txt', 'w') as file:
    for i in df2_merged.columns[:-4]:
        file.write(f"{i}\n")

In [75]:
from sklearn.preprocessing import LabelEncoder

# Define target variable
y = df2_merged["Predicted Time to Target (wks)"]

# Drop target column from features
X = df2_merged.drop(columns=["Predicted Time to Target (wks)"])

print(df2_merged.shape, X.shape, y.shape)
# Encode categorical variables if any
for col in X.select_dtypes(include=['object']).columns:
    X[col] = LabelEncoder().fit_transform(X[col].astype(str))

# Handle missing values
imputer = SimpleImputer(strategy='mean')
X_columns = X.columns  # Save column names before transformation
X_array = imputer.fit_transform(X)

X_array

(10119, 442) (10119, 441) (10119,)

/home/shaurya/ML_Project/project_venv/lib/python3.12/site-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['Duration Between Dietary Recall Interviews' 'Head BMI']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(

array([[0.00000000e+00, 7.35570000e+04, 1.68883279e+04, ...,
        1.71300000e+02, 7.83000000e+01, 6.45800000e+01],
       [1.00000000e+00, 7.35580000e+04, 1.79321439e+04, ...,
        1.76800000e+02, 8.95000000e+01, 6.87260000e+01],
       [2.00000000e+00, 7.35590000e+04, 5.96418129e+04, ...,
        1.75300000e+02, 8.89000000e+01, 6.75930000e+01],
       ...,
       [9.81000000e+03, 8.37290000e+04, 1.52725052e+04, ...,
        1.62300000e+02, 8.96000000e+01, 5.74490000e+01],
       [9.81100000e+03, 8.37300000e+04, 0.00000000e+00, ...,
        1.19100000e+02, 2.28000000e+01, 4.95920000e+01],
       [9.81200000e+03, 8.37310000e+04, 5.80567481e+03, ...,
        1.48100000e+02, 4.23000000e+01, 4.95920000e+01]],
      shape=(10119, 439))

In [76]:
df2_merged

,Unnamed: 0,Participant ID,Day 1 Weight,Two-Day Weight,Dietary Status,Examined Respondent,Breastfeeding,Dietary Interview,Interview Hour,Interview Day,...,Gas Stove Usage in Household,Sleep Quality Rating,Sleep Duration Per Night (Hours),Nap Frequency Per Week,Nap Duration (Minutes),Effort in Maintaining Health,Height (cm),Current Weight (kg),Predicted Time to Target (wks),Predicted Target Weight (kg)
0,0,73557,16888.327864,12930.890649,1,49.0,2.0,2.0,6.0,2.0,...,4.0,62.0,1.0,NaN,NaN,1.0,171.3,78.3,26.642,64.580
1,1,73558,17932.143865,12684.148869,1,59.0,2.0,2.0,4.0,1.0,...,4.0,28.0,1.0,NaN,NaN,1.0,176.8,89.5,41.934,68.726
2,2,73559,59641.812930,39394.236709,1,49.0,2.0,2.0,18.0,6.0,...,4.0,49.0,1.0,NaN,NaN,3.0,175.3,88.9,42.744,67.593
3,3,73560,142203.069917,125966.366442,1,54.0,2.0,2.0,21.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,137.3,32.2,10.540,49.592
4,4,73561,59052.357033,39004.892993,1,63.0,2.0,2.0,18.0,1.0,...,4.0,NaN,NaN,NaN,NaN,1.0,162.4,52.0,8.784,58.685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10114,9808,83727,14146.781331,10520.302070,1,59.0,2.0,2.0,8.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,171.3,71.8,15.808,64.339
10115,9809,83728,38750.761193,51815.103262,1,25.0,2.0,2.0,9.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,84.4,11.3,10.540,49.592
10116,9810,83729,15272.505199,10401.781170,1,59.0,2.0,2.0,1.0,6.0,...,4.0,55.0,1.0,NaN,NaN,3.0,162.3,89.6,53.776,57.449
10117,9811,83730,0.000000,NaN,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,119.1,22.8,10.540,49.592
10118,9812,83731,5805.674812,4339.132077,1,49.0,2.0,2.0,12.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,148.1,42.3,10.540,49.592

In [77]:
import numpy as np
import pandas as pd

def detect_cardiovascular_conditions(row):
    conditions = []
    
    # Blood Pressure
    systolic1 = row.get('Systolic BP1', 0)
    diastolic1 = row.get('Diastolic BP1', 0)
    
    # Get second and third readings if available for averaging
    systolic2 = row.get('Systolic BP2', 0)
    diastolic2 = row.get('Diastolic BP2', 0)
    systolic3 = row.get('Systolic BP3', 0)
    diastolic3 = row.get('Diastolic BP3', 0)
    
    # Calculate average if multiple readings are available
    count = 0
    systolic_sum = 0
    diastolic_sum = 0
    
    if systolic1 > 0:
        systolic_sum += systolic1
        diastolic_sum += diastolic1
        count += 1
    if systolic2 > 0:
        systolic_sum += systolic2
        diastolic_sum += diastolic2
        count += 1
    if systolic3 > 0:
        systolic_sum += systolic3
        diastolic_sum += diastolic3
        count += 1
    
    if count > 0:
        systolic_avg = systolic_sum / count
        diastolic_avg = diastolic_sum / count
        
        if systolic_avg >= 180 or diastolic_avg >= 120:
            conditions.append('Hypertensive Crisis')
        elif systolic_avg >= 140 or diastolic_avg >= 90:
            conditions.append('Stage 2 Hypertension')
        elif systolic_avg >= 130 or diastolic_avg >= 80:
            conditions.append('Stage 1 Hypertension')
        elif systolic_avg >= 120 and systolic_avg < 130 and diastolic_avg < 80:
            conditions.append('Elevated Blood Pressure')
        elif systolic_avg < 90 or diastolic_avg < 60:
            conditions.append('Hypotension')
    
    # Heart Rate / Pulse
    pulse = row.get('Pulse Rate', 0)
    if pulse > 0:  # Only if pulse has been recorded
        if pulse > 100:
            conditions.append('Tachycardia')
        elif pulse < 60:
            conditions.append('Bradycardia')
    
    # Cholesterol-related risks
    cholesterol = row.get('Cholesterol', 0)
    if cholesterol > 200:
        conditions.append('Hypercholesterolemia')
    
    return ', '.join(conditions) if conditions else 'None'

def detect_metabolic_issues(row):
    conditions = []
    
    # Diabetes risk factors
    sugar_intake = row.get('Total Sugar Intake (grams)', 0)
    if sugar_intake > 50:
        conditions.append('High Sugar Intake')
    
    carb_intake = row.get('Total Carbohydrate Intake (grams)', 0)
    if carb_intake > 300:
        conditions.append('High Carbohydrate Intake')
    
    return ', '.join(conditions) if conditions else 'None'

def detect_nutritional_deficiencies(row):
    conditions = []
    
    calcium = row.get('Total Calcium Intake (milligrams)', 0)
    if calcium < 800:
        conditions.append('Low Calcium Intake')
    
    iron = row.get('Total Iron Intake (milligrams)', 0)
    if iron < 8:
        conditions.append('Low Iron Intake')
    
    vitamin_c = row.get('Vitamin C', 0)
    if vitamin_c < 60:
        conditions.append('Low Vitamin C')
    
    vitamin_d = row.get('Vitamin D', 0)
    if vitamin_d < 20:
        conditions.append('Low Vitamin D')
    
    fiber = row.get('Total Fiber Intake (grams)', 0)
    if fiber < 25:
        conditions.append('Low Fiber Intake')
    
    protein = row.get('Total Protein Intake (grams)', 0)
    if protein < 50:
        conditions.append('Low Protein Intake')
    
    sodium = row.get('Total Sodium Intake (milligrams)', 0)
    if sodium > 2300:
        conditions.append('High Sodium Intake')
    
    return ', '.join(conditions) if conditions else 'None'

# Create a new dataframe with medical conditions
# Apply each detection function to the dataframe
medical_conditions_df = pd.DataFrame({
    'cardiovascular_conditions': df2_merged.apply(detect_cardiovascular_conditions, axis=1),
    'metabolic_issues': df2_merged.apply(detect_metabolic_issues, axis=1),
    'nutritional_deficiencies': df2_merged.apply(detect_nutritional_deficiencies, axis=1)
})

# Append the new columns to the original dataframe
df2_merged = pd.concat([df2_merged, medical_conditions_df], axis=1)

In [78]:
df2_merged.to_csv('datasets/fitness_dataset.csv', index=False)

In [79]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor

# Load dataset
df = pd.read_csv("datasets/fitness_dataset.csv")

# Drop unnecessary column
df.drop('Unnamed: 0', axis=1, inplace=True)

# Define target column
target_col = 'Predicted Time to Target (wks)'

# Drop ID if present
if 'Participant ID' in df.columns:
    df = df.drop(columns=['Participant ID'])

# Drop rows where target is NaN
df = df.dropna(subset=[target_col])

# Encode categorical columns
label_encoders = {}
for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Separate features and target
X = df.drop(columns=[target_col])
y = df[target_col]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(
    n_estimators=30,     # Fewer trees
    max_depth=10,        # Prevent very deep trees
    n_jobs=-1,           # Use all CPU cores
    random_state=42
)

model.fit(X_train, y_train)

# Get feature importances
importances = model.feature_importances_
features = X.columns
feature_importance = pd.Series(importances, index=features).sort_values(ascending=False)

# Get top 10 features
top_features = feature_importance.head(6).index.tolist()

# Create new DataFrame with top features + target
df_top = df[top_features + [target_col]]

df_top.drop(['Current Weight (kg)', 'Height (cm)'], axis=1, inplace=True)

# Display result
print(f"Top {len(df_top.columns) - 1} Important Features:")
for i in df_top.columns:
    print(i)
df_top.to_csv('datasets/best_feature_dataset.csv', index=False)

Top 4 Important Features:
Body Mass Index (BMI)
Body Weight (kg)
Predicted Target Weight (kg)
Body Height (cm)
Predicted Time to Target (wks)

/tmp/ipykernel_773/4024549080.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_top.drop(['Current Weight (kg)', 'Height (cm)'], axis=1, inplace=True)

In [80]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, make_scorer
from sklearn.model_selection import cross_val_score, KFold

# Load your dataset
df = pd.read_csv('datasets/best_feature_dataset.csv')
print("df.shape:", df.shape)

# Define the target
target = 'Predicted Time to Target (wks)'
X = df.drop(columns=[target])
y = df[target]

# Convert categorical variables to dummies if needed
X = pd.get_dummies(X, drop_first=True)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = HistGradientBoostingRegressor(random_state=42)
model.fit(X_train, y_train)

# Predict and evaluate
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
mse_train=  mean_squared_error(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_test_pred)
r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f'Mean Squared Error for train: {mse_train}')
print(f'Mean Squared Error for test: {mse_test}')
print(f'RÂ² Score for train: {r2_train}')
print(f'RÂ² Score for test: {r2_test}')

cv = KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model, X, y, cv=cv, scoring=make_scorer(r2_score))

print("Cross-validated RÂ² scores:", scores)
print("Mean RÂ² score:", scores.mean())
print("Standard deviation:", scores.std())

df.shape: (9361, 5)

Mean Squared Error for train: 0.1852591168577041
Mean Squared Error for test: 0.3186830739724879
RÂ² Score for train: 0.9994973269970263
RÂ² Score for test: 0.9991459508466368
Cross-validated RÂ² scores: [0.99914595 0.99902159 0.99926577 0.9992655  0.99918859]
Mean RÂ² score: 0.9991774799271603
Standard deviation: 9.051082216093277e-05

In [81]:
def merge_conditions(row):
    parts = [
        row['cardiovascular_conditions'],
        row['metabolic_issues'],
        row['nutritional_deficiencies']
    ]
    # Filter out 'None' and empty strings
    parts = [p for p in parts if p and p.strip().lower() != 'none']
    return ', '.join(parts)

df2_merged['diseases'] = df2_merged.apply(merge_conditions, axis=1)

In [82]:
import re

def remove_numbers(text):
    temp_list = text.split()
    temp_list = [word for word in temp_list if not word.isdigit()]
    return ' '.join(temp_list)

df2_merged['diseases'] = df2_merged['diseases'].apply(remove_numbers)

In [83]:
df['Disease'] = df2_merged['diseases']

In [84]:
df.to_csv('datasets/data_to_train.csv')

In [85]:
df

,Body Mass Index (BMI),Body Weight (kg),Predicted Target Weight (kg),Body Height (cm),Predicted Time to Target (wks),Disease
0,26.7,78.3,64.580,171.3,26.642,"Hypercholesterolemia, Low Calcium Intake, Low ..."
1,28.6,89.5,68.726,176.8,41.934,"Stage Hypertension, Hypercholesterolemia, Low ..."
2,28.9,88.9,67.593,175.3,42.744,"Stage Hypertension, Low Calcium Intake, Low Ir..."
3,17.1,32.2,49.592,137.3,10.540,"Hypotension, Low Calcium Intake, Low Iron Inta..."
4,19.7,52.0,58.685,162.4,8.784,"Stage Hypertension, Low Calcium Intake, Low Ir..."
...,...,...,...,...,...,...
9356,24.5,71.8,64.339,171.3,15.808,"Hypotension, Low Calcium Intake, Low Iron Inta..."
9357,15.9,11.3,49.592,84.4,10.540,"Stage Hypertension, Hypercholesterolemia, Low ..."
9358,34.0,89.6,57.449,162.3,53.776,"Stage Hypertension, Hypercholesterolemia, Low ..."
9359,16.1,22.8,49.592,119.1,10.540,"Stage Hypertension, Hypercholesterolemia, Low ..."
9360,19.3,42.3,49.592,148.1,10.540,"Hypercholesterolemia, Low Calcium Intake, Low ..."